name: model-training
on: [pull_request]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py

          # ls -la
          # echo "First"
          # cat metrics.txt >> report.md
          # echo "Second"
          # cml-publish confusion_matrix.png --md >> report.md
          # echo "Cat:"
          # cat report.md
          # echo "Third"
          # cml-send-comment report.md
          # Write your CML report
          echo "This works yet?" >> report.md
          cml-send-comment report.md